import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Header } from "../src/components/Header";
import { NoteList } from "../src/components/NoteList";
import styles from "../styles/Home.module.scss";
import defaultStyles from "../styles/default.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Journaliser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.content}>
          <h2 className={defaultStyles.title}>Daily Log</h2>
          <NoteList
            notes={[
              {
                body: "Hello world",
                createdAt: new Date(),
                collectionId: null,
                id: "1",
                completed: false,
                noteType: "TASK",
              },
              {
                body: "Hello world, again",
                createdAt: new Date(),
                collectionId: null,
                id: "1",
                completed: true,
                noteType: "NOTE",
              },
              {
                body: "Hello world, again, again",
                createdAt: new Date(),
                collectionId: null,
                id: "1",
                completed: false,
                noteType: "EVENT",
              },
            ]}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
